version: "3"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"

volumes:
  db-data:
secrets:
  db-password:
    file: secrets/pg-password.txt
