services:
  server:
    build:
      context: .
      args:
        SVC_PORT: "8000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:academy1164@db:5432/postgres?schema=public
      REDIS_URL: redis://cache:6379/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
volumes:
  db-data:
secrets:
  db-password:
    file: secrets/password.txt
  node-env:
    file: secrets/node-env.txt
